theme = 'notetoself-inspired'
baseURL = 'https://dryjim.com/'
languageCode = 'en-gb'
title = 'DryJim Newsletter'

[params]
  description = "Your weekly dose of insight and perspective"
  author = "Jim"
  tagline = "Thoughtful commentary on the world around us"
  
  # testing branch deployment
  # Social links (optional)
  # github = "https://github.com/yourusername"
  # twitter = "https://twitter.com/yourusername"
  
  # Newsletter specific
  email = "subscribe@dryjim.com"  # Update when you have email setup
